recipes-website/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('recipes.urls')),
]

urlpatterns  += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

recipes/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = 'recipes'

urlpatterns = [
    path('',  views.home, name='home'),
    path('recipes/<int:id>/',  views.recipe, name='recipe'),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

recipes/models.py
from django.db import models
from django.contrib.auth.models import User

class Category(models.Model):
    
    name = models.CharField(max_length=65)
    
    def __str__(self):
        return self.name
class Recipe(models.Model):
    
    title = models.CharField(max_length=65)
    description = models.CharField(max_length=165)
    slug = models.SlugField()
    preparation_time = models.IntegerField()
    preparation_time_unit = models.CharField(max_length=65)
    servings = models.IntegerField()
    servings_unit = models.CharField(max_length=65)
    preparation_steps = models.TextField()
    preparation_steps_is_html = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    is_published = models.BooleanField(default=False)
    cover = models.ImageField(upload_to='recipes/covers/%Y/%m/%d/')
    
    category = models.ForeignKey(Category, on_delete=models.SET_NULL, null=True)
    author = models.ForeignKey(User , on_delete=models.SET_NULL, null=True)
    
    def __str__(self):
        return self.title

recipes/views.py
from django.shortcuts import render
from django.http import HttpResponse
from  utils.recipes.factory import make_recipe
from .models import Recipe

def home(request):
    recipes = Recipe.objects.all().order_by('-id')
    return render(request, 'recipes/pages/home.html', context={
        'recipes': recipes,
        'detail_page': False
    })
def recipe(request, id):
    return render(request, 'recipes/pages/recipe-view.html', context={
        'recipe': Recipe.objects.get(id=id),
        'detail_page': True
    })
    

recipes/templates/recipes/pages/home.html
{% extends 'recipes/partials/base.html' %}

{% block title %}Home{% endblock title %}
{% block content %}

<div class="main-content main-content-list container">
  {% for recipe in recipes %}
      {% include "recipes/partials/recipe.html" %}
  {% endfor %}
</div>

{% endblock content %}

recipes/templates/recipes/pages/recipe-view.html
{% extends 'recipes/partials/base.html'%}

{% block title %}Teste{% endblock title %}

{% block content %}
<div class="main-content main-content-detail container">
    {% include 'recipes/partials/recipe.html' %}
</div>
{% endblock content %}

recipes/templates/recipes/partials/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt_BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />    

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/brands.min.css" integrity="sha512-58P9Hy7II0YeXLv+iFiLCv1rtLW47xmiRpC1oFafeKNShp8V5bKV/ciVtYqbk2YfxXQMt58DjNfkXFOn62xE+g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/fontawesome.min.css" integrity="sha512-v8QQ0YQ3H4K6Ic3PJkym91KoeNT5S3PnDKvqnwqFD1oiqIl653crGZplPdU5KKtHjO0QKcQ2aUlQZYjHczkmGw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
    <title>{% block title%}{% endblock title%}</title>
</head>

<body>
    {% include "recipes/partials/header.html" %}
    {% include "recipes/partials/search.html" %}
    <main class="main-content-container">
       {% block content %}{% endblock content %}
    </main>
    </div>
  <footer class="main-footer">
      <a href="https://github.com/joaovitorfdev"><i class="fa-brands fa-github"></i>  joaovitorfdev</a>
      <a href="https://www.djangoproject.com/"><i class="fa-solid fa-code"></i>  Made with Django</a>
  </footer>
</body>

</html>

recipes/templates/recipes/partials/footer.html
<footer class="main-footer">
    <a href="https://github.com/joaovitorfdev"><i class="fa-brands fa-github"></i>  joaovitorfdev</a>
    <a href="https://www.djangoproject.com/"><i class="fa-solid fa-code"></i>  Made with Django</a>
</footer>

recipes/templates/recipes/partials/head.html
{% load static %}
<!DOCTYPE html>
<html lang="pt_BR">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/all.min.css" integrity="sha512-Evv84Mr4kqVGRNSgIGL/F/aIDqQb7xQ2vcrdIwxfjThSH8CSR7PBEakCr51Ck+w+/U6swU2Im1vVX0SVk9ABhg==" crossorigin="anonymous" referrerpolicy="no-referrer" />    

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/brands.min.css" integrity="sha512-58P9Hy7II0YeXLv+iFiLCv1rtLW47xmiRpC1oFafeKNShp8V5bKV/ciVtYqbk2YfxXQMt58DjNfkXFOn62xE+g==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.7.2/css/fontawesome.min.css" integrity="sha512-v8QQ0YQ3H4K6Ic3PJkym91KoeNT5S3PnDKvqnwqFD1oiqIl653crGZplPdU5KKtHjO0QKcQ2aUlQZYjHczkmGw==" crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'recipes/css/styles.css' %}">
    <title>Recipes</title>
</head>

recipes/templates/recipes/partials/header.html
<header class="main-header-container">
    <div class="main-header container">
        <h1>
            <a class="main-logo" href="/">
                <i class="fa-solid fa-utensils main-logo-icon"></i>
                <span class="main-logo-text">Recipes</span>
            </a>
        </h1>
    </div>
</header>

recipes/templates/recipes/partials/recipe.html
<div class="recipe recipe-list-item">
    <div class="recipe-cover">
        <img src="{{recipe.cover.url}}"
            alt="texto imagem relativo">
    </div>
    <div class="recipe-tittle-container">
        <h2 class="recipe-title">{{recipe.title}}</h2>
    </div>
    <div class="recipe-author">
        <span class="recipe-author-item">
            <a href="/user"> <i class="fa-solid fa-user"> </i>
                {{recipe.author.first_name}}</a>
        </span>
        </span>

        <span class="recipe-author-item">
            <i class="fa-solid fa-calendar"> </i>
            01/10/2007 at 15:20
        </span>

        <span class="recipe-author-item">
            <a href="/categoryes"> <i class="fa-solid fa-layer-group"> </i>
                Breakfest</a>
        </span>
    </div>
    <div class="recipe-content">
        <p>{{recipe.description}}</p>
    </div>
    {% if detail_page %}
    <div class="preparation-steps">
       {{recipe.preparation_steps|linebreaksbr}} 
    </div>
    {% endif %}
    <div class="recipe-meta-container">
        <div class="recipe-meta recipe-preparation">
            <h3> <i class="fa-solid fa-clock"> </i> Preparing time</h3>

            <div class="recipe-meta-text">
                {{recipe.preparation_time}} minutes
            </div>
        </div>
        <div class="recipe-meta recipe-portions">
            <h3><i class="fa-solid fa-user-group"></i> Portions</h3>

            <div class="recipe-meta-text">
                {{recipe.servings}} portions
            </div>
        </div>
    </div>
    {% if not detail_page %}
    <footer class="recipe-footer">
        <a href="{% url 'recipes:recipe' recipe.id %}" class="recipe-footer-btn"><i class="fa-solid fa-eye"></i> See more</a>
    </footer>
    {% endif %}

 
</div>

recipes/templates/recipes/partials/search.html
<div class="search-container">
    <div class="container">
        <form action="" class="search-form">
         <input type="search" class="search-input" name="search">
         <button type="submit" class="search-button"> <i class="fa-solid fa-search main-logo-icon"></i></button>
        </form>
    </div>
</div>